version: '3.9'

services:
  server:
    image: vlrpi/rpi-teamcity-server:debian-bullseye-2021.1
    restart: always
    container_name: teamcity_server
    ports:
      - "8111:8111"
    volumes:
      - teamcity_server_storage:/root/BuildServer
    networks:
      - teamcity_network

  agent-alice:
    image: vlrpi/rpi-teamcity-agent-dotnet:debian-bullseye-tc-2021.1-dotnet-supported
    restart: always
    container_name: teamcity_agent
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - server
    networks:
      - teamcity_network

networks:
  teamcity_network:
    name: teamcity_network

volumes:
  teamcity_server_storage:
    name: teamcity_server_storage
