version: '3.7'

services:
  rpi4-base-image:
    build: balenalib-aarch64-debian-bullseye-dotnet-5.0-sdk-run
    container_name: rpi4-base-image
    restart: "no"
    command: "true"
    networks: 
      - teamcity_network

  jdk11:
    build: jdk11
    container_name: jdk11
    command: "true"
    restart: "no"
    networks:
      - teamcity_network
    depends_on: 
      - rpi4-base-image

  server:
    build: server
    restart: always
    container_name: teamcity_server
    depends_on:
      - jdk11
    ports:
      - "8111:8111"
    volumes:
      - teamcity_server_storage:/root/BuildServer
    networks:
      - teamcity_network

  agent-alice:
    build: agent-alice
    restart: always
    container_name: teamcity_agent
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - server
    networks:
      - teamcity_network

networks:
  teamcity_network:
    name: teamcity_network

volumes:
  teamcity_server_storage:
    name: teamcity_server_storage